spring.application.name=smart-campus-attendance-system

# Active profile - override with: -Dspring.profiles.active=prod
spring.profiles.active=prod

# JPA shared settings
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false